### ISSUE TITLE
thresholds

### ISSUE THREAD

**Issue by siudej** [micah541/Ricci#12]
We normalize sqdist in L1, but the thresholds for clustering are set absolutely. So when the matrix gets large, the elements get small and thresholds become too large.

Shouldn't thresholds be relative to initial_L1 norm?

**Comment by siudej** [comment]
It might be best to reevaluate scaling on all steps of the procedure. We should try to make sure the algorithm runs in exactly the same way on rescaled data. This either means that `t` has to depend on some norm of the data, all data needs to be renormalized to begin with.

**Comment by micah541** [comment]
added in L_inf scaling
