### ISSUE TITLE
What is gmpy2 is not available?

### ISSUE THREAD

**Issue by micah541** [micah541/Ricci#5]
Anaconda doesn't seem to find gmpy2 for my windows.  Can we turn this off and still run things?

**Comment by siudej** [comment]
pip install gmpy2 
will install gmpy2 in anaconda. Maybe pip.exe in windows.

I will add some try/except clauses to handle this.

**Comment by micah541** [comment]
Yeah I figured it out.  I was first getting a message saying conda could find it.    Thanks
